### ISSUE TITLE
DELETE endpoint throws 404 Not Found for newly added data using POST endpoint

### ISSUE THREAD

**Issue by ramukima** [corenova/yang-cord#6]
Followed steps -
1. Add a new subscriber
2. Delete Subscriber

```
bash-4.3$ curl -i -X DELETE localhost:5050/cord:subscriber/12
HTTP/1.1 404 Not Found
X-Powered-By: Express
Date: Sat, 13 Aug 2016 21:10:21 GMT
Connection: keep-alive
Content-Length: 0

bash-4.3$ curl localhost:5050/subscriber
{
  "subscriber": [
    {
      "id": 1,
      "service-specific-id": 1000,
      "humanReadableName": "cordSubscriber-1",
      "status": "enabled",
      "demo": false,
      "uplink-speed": 1000000000,
      "downlink-speed": 1000000000,
      "kind": "generic"
    },
    {
      "id": 2,
      "service-specific-id": 1001,
      "humanReadableName": "cordSubscriber-2",
      "status": "enabled",
      "demo": false,
      "uplink-speed": 1000000000,
      "downlink-speed": 1000000000,
      "kind": "generic"
    },
    {
      "id": 12,
      "service-specific-id": 2020,
      "demo": true
    }
  ]
}bash-4.3$
```

**Comment by sekur** [comment]
The issue was with the way **key** was being treated...  The _datakey_ for the list object should've been the fully-qualified YANG label such as `cord-core:subscriber` but was using what was passed in as part of the URI.  If the initial POST request was done via `/cord-core:subscriber` instead of `/cord:subscriber` the proper creation/entry would've taken place and it would be found on subsequent GET.
I've applied fix inside `yang-js` to change how `Model.access` returned the _key_ to always use the _expr.datakey_ instead of last known xpath tag name.  Will need to think this through again to assess whether the _key_ has other prior intended purpose.
